### ISSUE TITLE
Sun rapidly blinking between positions

### ISSUE THREAD

**Issue by kitsu** [SilentChaos512/ExtendedDays#10]
With the latest update JourneyMap clock doesn't freeze at scheduled time extensions, but the sun blinks rapidly in the sky. It looks like every other tick the sun is shown in a higher/lower position. Is this an interaction with Astral Sorcery's custom sky rendering?

### Versions

Minecraft Version: 1.12.2
Forge: 14.23.1.2587
Extended Days Version: 0.2.0
Silent Lib Version: 2.2.16

**Comment by SilentChaos512** [comment]
Reproducible with just Extended Days, Silent Lib, and Astral Sorcery. Adding 0 to AS's "weakSkyRenders" list seems to fix the issue. But I'm not familiar with the mod, so it may have some negative effects I'm not aware of.

**Comment by ElvenChaos** [comment]
Will there be an option to use the old "pause then play" style of sky this mod used to do, in case of new rendering breaking things, or just preference to allow full sky rendering of other mods (astral)?

**Comment by SilentChaos512** [comment]
There's already a config for that, under client/sky.

**Comment by ElvenChaos** [comment]
Sorry, I overlooked that entry.

**Comment by kitsu** [comment]
Just confirming weakSkyRenders does solve the problem. I haven't gotten far into AS yet, but the sky rendering mechanics are mainly cosmetic (there are alternative block based methods to access any sky info (except eclipses?)).
