### ISSUE TITLE
[compatibility] Comforts Mod

### ISSUE THREAD

**Issue by SimulatorSia** [SilentChaos512/ExtendedDays#15]
Minecraft Version: 1.12.2
Extended Days Version: 0.2.2-15
Silent Lib Version: 2.2.16-97

With the comforts mod, when you sleep on a hammock during the day, it's supposed to change time to twilight/evening. It instead sets it to the beginning of the day again.

**Comment by SimulatorSia** [comment]
The owner of the comforts mod says it's an issue on your end. Please don't decline fixing it maybe?<3


https://github.com/TheIllusiveC4/Comforts/issues/10

**Comment by SilentChaos512** [comment]
Yes, Extended Days has issues with basically all mods that modify sleep. I'm looking for a fix.

**Comment by SimulatorSia** [comment]
:0 thank you!!!<3<3!!11!!1<3!!!

**Comment by SilentChaos512** [comment]
Seems to work correctly in 0.2.3. If anything is still off, please re-open the issue.

**Comment by SimulatorSia** [comment]
Thank you so much!!! I thought it'd be like one of those issues no one would help me with. Your mod is so much more polished than the russian version
