### ISSUE TITLE
Intermittent Crash on World Load

### ISSUE THREAD

**Issue by Tetrajak** [SilentChaos512/ExtendedDays#16]
### Versions

Minecraft Version: 1.12.2
Extended Days Version: 0.2.3-17
Silent Lib Version: 2.2.16-97

### Expected behavior

- The world loads as normal

### Actual behaviour

- Every so often, loading into a world in single player will crash the client.
Crash Log: https://pastebin.com/Cd6a2vMh
Extended Periods:
6000 10
15000 -5

### Steps to reproduce the problem

1. Start a single player world
2. Leave the world
3. Optionally restart MC
4. Load into the world

**Comment by IBeCrayZ** [comment]
I’m pretty sure I got this crash a little while back (latest mod version 0.2.3-17) but I have since changed what mods I have installed. 

It definitely crashed on loading the world though, showing a similar crash log to Tetrajaks.
