### ISSUE TITLE
Blinking night

### ISSUE THREAD

**Issue by cam72cam** [SilentChaos512/ExtendedDays#19]
### Versions

Minecraft Version: 1.12.2
Extended Days Version: 0.2.4-20
Silent Lib Version: 2.2.18-100

### Expected behavior

- Nights don't blink on and off

### Actual behaviour

- Nights visually blink to day and then back

### Steps to reproduce the problem

1. Add mod to my pack
2. Run with mod for a week or so
3. ...
4. Profit

https://giant.gfycat.com/MindlessAppropriateAlbacoretuna.webm

Sleeping in a bed seems to fix it.

**Comment by SilentChaos512** [comment]
I have a couple of questions:
1. Single player or server?
2. Does it happen every night or just occasionally?
3. Is your world ever laggy? (Warnings about ticks taking too long, mined blocks taking a while to drop, etc.) Not sure if that would make a difference, but it might.

**Comment by cam72cam** [comment]
1. Server
2. Occasionally
3. Nope

**Comment by KorDum** [comment]
With SilentLib 2.2.16-97 bug doesn't show up.

**Comment by SilentChaos512** [comment]
@KorDum Not sure why that would be the case. Are you also using Extended Days 0.2.4?

**Comment by KorDum** [comment]
Yes, indeed.

**Comment by fabbe50** [comment]
@KorDum Do you have Astral Sorcery installed? Cause I believe that's what's causing the issue in my case since both mods are overriding the sky renderer.

**Comment by fabbe50** [comment]
Just realized the blinking isn't the same in your gif as on my screen, so maybe not. But I still believe it's Astral Sorcery in my case.

**Comment by SilentChaos512** [comment]
This should be fixed in 0.2.5.

**Comment by KorDum** [comment]
So far, everything is ok
