### ISSUE TITLE
Day Progression Stuck at 0

### ISSUE THREAD

**Issue by dragonshardz** [SilentChaos512/ExtendedDays#22]
Please follow the template for bug reports. Include links to crash reports, if there are any. Feature suggestions and questions may remove all sections.

### Versions

Minecraft Version: 1.12.2
Extended Days Version: 0.2.4-20
Silent Lib Version: 2.2.18-100

### Expected behavior

- Days (as displayed ingame via F3) advance normally and the moon goes through its different phases. 

### Actual behavior

- Days are reset to 0 at dawn, preventing the moon phase from advancing and breaking progression for mods (like Astral Sorcery and Thaumcraft 6) that have progression linked to moon phases.

### Steps to reproduce the problem

1. Run Extended Days, and either Thaumcraft or Astral Sorcery
2. Note that the moon never changes away from full, and the day is perpetually 0 in the F3/debug screen.
3. Adding time by `/time add 24000` does advance the day by 1, but this is reset as soon as the extended period occurs.

**Comment by SilentChaos512** [comment]
Couple of questions:
1. Singleplayer or server?
2. Is the Extended Days sky renderer disabled (client/sky in config)
3. Any other config changes?

**Comment by dragonshardz** [comment]
1. Server
2. Sky renderer is disabled clientside and serverside
3. Changed from default extended periods to just an extra 20 minutes of day at noon.

**Comment by dragonshardz** [comment]
Hi, any progress on this?

**Comment by SilentChaos512** [comment]
I'll take another look at it this weekend. One more question: have you made sure your client has the same config file as the server?

**Comment by dragonshardz** [comment]
Yes, I have made sure the config files on both the server and client are identical.

**Comment by SilentChaos512** [comment]
Please test with version 0.2.5 and let me know if the issue is fixed or not.

**Comment by fabbe50** [comment]
This is fixed.

**Comment by dragonshardz** [comment]
Can confirm, this issue is resolved. Many thanks.
