### ISSUE TITLE
Extended Days and Astral Sorcery causes flickering sky.

### ISSUE THREAD

**Issue by fabbe50** [SilentChaos512/ExtendedDays#23]
Please follow the template for bug reports. Include links to crash reports, if there are any. Feature suggestions and questions may remove all sections.

### Versions

Minecraft Version: 1.12.2
Extended Days Version: 0.2.4
Silent Lib Version: 2.3.2

### Expected behavior

- Non-flickery sky.

### Actual behavior

- The sky is flickering back and forth between the Extended Days renderer and Astral Sorcery's sky renderer. Could use with some compatibility layer or something.

### Steps to reproduce the problem

1. Have Extended Days and Astral Sorcery in the client.
2. Load up a world and watch the light show.
3. ...
4. Profit

**Comment by SilentChaos512** [comment]
Have you tried version 0.2.5?

**Comment by fabbe50** [comment]
It fixed the sky glitching back and forth. Thanks
