### ISSUE TITLE
server issue?

### ISSUE THREAD

**Issue by NorNogaAdmin** [SilentChaos512/ExtendedDays#27]
Please follow the template for bug reports. Include links to crash reports, if there are any. Feature suggestions and questions may remove all sections.

### Versions

Minecraft Version: 1.12.2
Extended Days Version: 2.7.25
Silent Lib Version: 3.0.4-150

### Expected behavior

- Server would start

### Actual behaviour

- server is not starting with extended days, removing the mod lets server start

### Steps to reproduce the problem
unknown

[crash-2018-09-10_00.35.57-server.txt](https://github.com/SilentChaos512/ExtendedDays/files/2365170/crash-2018-09-10_00.35.57-server.txt)
[debug.log](https://github.com/SilentChaos512/ExtendedDays/files/2365171/debug.log)
[latest.log](https://github.com/SilentChaos512/ExtendedDays/files/2365172/latest.log)

**Comment by SilentChaos512** [comment]
Seems it was Silent Lib bug. I'm uploading a new version now, should be available soon.

**Comment by NorNogaAdmin** [comment]
Looks to be fixed
