### ISSUE TITLE
[Request] Allow negative periods

### ISSUE THREAD

**Issue by Tetrajak** [SilentChaos512/ExtendedDays#4]
One way you could allow for shorter days/nights would be the use of a negative period that would, at the given MC time, skip forward the given amount of ticks.

**Comment by SilentChaos512** [comment]
The only problem with that is that the sun/moon would jump from one point to another, just like when using /time set. It's doable, but ugly.

**Comment by Tetrajak** [comment]
Certainly, but the sun/moon stopping in place is also not exactly desirable if the goal is pleasant aesthetics. I figure, while your mod has yet to solve that particular problem, the sun/moon jumping across the sky is an acceptable loss for the feature.

**Comment by SilentChaos512** [comment]
Fair enough, I'll add it. :)

No guarantee I'll find a fix for sky rendering without ASM, but I have a couple of clues as to what I could do.

**Comment by Tetrajak** [comment]
Personally, I would be fine with this being a core mod in order to achieve a slowing/quickening of the skybox for aesthetics.
