### ISSUE TITLE
Server Console Spam - ExtendedDaysSavedData#writeToNBT

### ISSUE THREAD

**Issue by rckymtnrfc** [SilentChaos512/ExtendedDays#5]
Minecraft Version: 1.12.2
Extended Days Version: 1.12-0.1.0-3
Silent Lib Version: 1.12-2.2.16-97

I'm seeing a message every 45 seconds on the server console:
[Extended days]: ExtendedDaysSavedData#writeToNBT

Wondering if that could be shut off, it's a bit excessive, imo.

Thanks!

**Comment by SilentChaos512** [comment]
Some debug text that slipped through. I'll remove it for next version, it's not needed.

**Comment by rckymtnrfc** [comment]
Thanks!
