### ISSUE TITLE
Does not work with Morphous - 1.12.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [SilentChaos512/ExtendedDays#7]
When you go to sleep the day does not change. You just wake back up.

**Comment by SilentChaos512** [comment]
Seems to be reproducible with and without Morpheus, but only during extended periods.

**Comment by SilentChaos512** [comment]
Version 0.1.2 should be available for download soon. Let me know if it fixes the Morpheus issue, it's a bit hard for me to test.
